---
- name: apt-get update
  apt:
    update_cache=yes
    autoclean=no
    autoremove=no
    cache_valid_time=86400

- name: Install toys
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - kodi
    - eric
